Feature/file upload
lblod/frontend-gelinkt-notuleren pull request #152
Opened 2021-07-12 08:15 UTC by Asergey91

further work on attachments

2021-07-14 14:32 UTC, nvdk commented
@lagartoverde : some missing semi's in app/services/document-service.js

2021-07-14 14:34 UTC, lagartoverde commented
Oh, I didn't check the semis yet, this is not ready, the function to get the decisions only runs when opening the modal, I will solve that next now that I finished the prepublisher

2021-07-15 09:09 UTC, lagartoverde commented
Ready for review now :)

2021-07-16 14:48 UTC, abeforgit reviewed
Looks ok from what I understand of it. Seems to work as well.

May or may not be an issue:
when adding attachments from the draft-decision screen, the "besluit" select box is always empty, even when it does show a value in the zitting view.

2021-07-19 13:53 UTC, nvdk requested changes
- Some small remarks on formatting
- I'd recommend abstracting the extractDecisions part that's present in both getDescription and getDecisions in the document service
- attachment type "regelgevend" is only possible for an attachment linked to a decision

2021-07-19 13:53 UTC, nvdk commented on app/controllers/agendapoints/edit.js
> +  @tracked uploading=false;
please mind the formatting

2021-07-19 13:53 UTC, nvdk commented on app/controllers/meetings/edit/treatment.js
> +  @tracked uploading=false;
formatting

2021-07-19 13:53 UTC, nvdk commented on app/services/document-service.js
> +    const node = document.createElement('body');
this shares quite a bit of logic with getDescription which can be abstracted

2021-07-20 12:25 UTC, nvdk approved these changes

2021-07-20 12:25 UTC, merged