Save document title after edit
lblod/frontend-gelinkt-notuleren pull request #337
Opened 2022-10-06 11:57 UTC by elpoelma

This ensures that the title of the document is saved just after having edited it. An additional save of the document is no longer required.

2022-10-11 11:58 UTC, nvdk commented
one consideration is that this doesn't create a new version of the document, which is different from before. open question whether this is what a user expects. (phrased another way: do title changes warrant a new version?)

2022-10-18 07:40 UTC, nvdk commented
@elpoelma can you fix the merge conflict?

2022-10-18 08:12 UTC, elpoelma commented
> @elpoelma can you fix the merge conflict?

Done, can this be merged?

2022-10-18 13:08 UTC, nvdk commented
I'm hesitant because of the above remark :)

2022-10-21 09:13 UTC, abeforgit commented
semantically, I'd say yes, title changes warrant a new version
versions are pretty transparent to the user anyway

2022-10-24 12:42 UTC, nvdk requested changes
looked into this a bit more and we were already saving on onSubmit as far as I can see, so we should clean this up. because now we are calling the component with 
```js
      <EditorDocumentTitle @title={{@editorDocument.title}} @editActive={{@editorDocument.isNew}} 
        @onChange={{this.updateDocumentTitle}} @onSubmit={{this.saveDocument}}  @onCancel={{this.resetDocument}} 
```
and both onSubmit and onChange save the document ? at the very least this should be cleaned up.

2022-10-24 13:28 UTC, nvdk commented
I've reworked this a bit + fixed some other stuff I ran into, needs a proper review @elpoelma :)

2022-10-24 14:44 UTC, nvdk commented on app/components/app-chrome.js
> +  async resetDocument() {
woops I think this bit is no longer relevant and can go

2022-10-25 14:00 UTC, elpoelma commented
There was some small issue in the `cancel` method, otherwise now it seems to work well. TItle edits also add a new version correctly now which shows up in the revisions tab.

2022-10-25 14:19 UTC, elpoelma commented
I'll update the reglementaire bijlage frontend in order to have the same workflow tomorrow.

2022-10-25 14:39 UTC, nvdk commented on app/components/editor-document-title.js
> +    console.log(event, this.title);
```suggestion
```

2022-10-25 14:42 UTC, merged