Don't allow participant list insertion if the chairman is not present
lblod/frontend-gelinkt-notuleren pull request #388
Opened 2022-12-14 10:18 UTC by lagartoverde

2022-12-16 13:55 UTC, abeforgit requested changes
Just a smal QoL comment, works well otherwise
OK to merge for me, moving the alert is optional

2022-12-16 13:55 UTC, abeforgit commented on app/components/participation-list/modal.hbs
> +      {{#if this.error}}
I would put this error next to the "insert" button

atm when you are scrolled down, you don't see the error and it feels like the insert button just doesnt work

2022-12-18 19:34 UTC, abeforgit requested changes
come to think of it, wouldn't it be better to simply disable the present toggle if the mandatee = the chairman?

We have no backup flow for when they do set the chairman as absent, we simply don't allow them to proceed. So why even have the option in the first place?

2022-12-19 13:32 UTC, lagartoverde commented
I have made the changes you suggested, also kept the message and moved the error just in case, or if we want to add more errors to it

2022-12-21 09:31 UTC, elpoelma approved these changes
Works as expected.

2022-12-21 14:45 UTC, merged