Make title error visible and wrap when content is long
lblod/frontend-gelinkt-notuleren pull request #390
Opened 2022-12-16 14:43 UTC by lagartoverde

Solves https://binnenland.atlassian.net/browse/GN-2674

2022-12-18 19:06 UTC, abeforgit requested changes

2022-12-18 19:06 UTC, abeforgit commented on app/components/editor-document-title.hbs
> +          {{#if this.error}}
You can put the if statement inside the class value here

2022-12-18 19:06 UTC, abeforgit commented on app/components/editor-document-title.hbs
> +              placeholder="Naamloos document"
i18n please

2022-12-18 19:07 UTC, abeforgit requested changes

2022-12-18 19:07 UTC, abeforgit commented on app/components/editor-document-title.hbs
> +    {{limit-content this.title 70}}
probably want some way to see the full title when read-only. (when not read-only, you can see it by editing it)

2022-12-21 09:40 UTC, elpoelma approved these changes
Works as expected

2022-12-21 14:53 UTC, merged