updated ember-data to 3.28.12
lblod/frontend-gelinkt-notuleren pull request #431
Opened 2023-02-22 12:57 UTC by lagartoverde

Seems to solve the problems with the participation list, https://binnenland.atlassian.net/browse/GN-4118

2023-02-22 13:48 UTC, elpoelma requested changes
Secretaries of a meeting are not correctly fetched. The following error is displayed: 
![image](https://user-images.githubusercontent.com/24712836/220638647-eff489b8-732e-4665-857d-ac5e032d4a2e.png)

2023-02-27 14:48 UTC, nvdk commented
I think it would be better to await the functionaris higher up in the power select or make sure it's loaded in loadData

2023-05-05 16:09 UTC, abeforgit requested changes

2023-05-05 16:09 UTC, abeforgit commented on app/models/functionaris.js
> +export default class FunctionarisModel extends MandatarisModel {
why did you do this? and don't we need to set polymorphic on some relationships then?

2023-05-05 16:09 UTC, abeforgit commented on app/components/participation-list.hbs
> +      {{t "participation-list.secretaris-label"}} <strong></strong>
theres an empty strong tag here

2023-05-05 16:09 UTC, abeforgit commented on package.json
> +    "ember-data": "~3.28.12",
could you bump to 3.28.13 while you're at it

2023-05-19 12:39 UTC, lagartoverde commented
@elpoelma is this finished? Because it looks good to me, and it works, so if it is, you can merge

2023-05-22 07:20 UTC, elpoelma commented
> I think it would be better to await the functionaris higher up in the power select or make sure it's loaded in loadData

I agree, I will try to look into this in this PR, or a future PR.

2023-05-22 07:33 UTC, elpoelma commented
> > I think it would be better to await the functionaris higher up in the power select or make sure it's loaded in loadData
> 
> I agree, I will try to look into this in this PR, or a future PR.

I honestly also don't see why the `await` would be needed, as the `functionaris`-models are already resolved in the `loadData` function.

2023-05-24 12:54 UTC, abeforgit requested changes
- some problem with inverses when loading the people present at the meeting
![image](https://github.com/lblod/frontend-gelinkt-notuleren/assets/16419862/1b0a7ae1-7545-4f4c-9619-19ce2351f87d)

kind of breaks the whole meeting page

2023-05-25 07:22 UTC, elpoelma commented
> * some problem with inverses when loading the people present at the meeting
>       ![image](https://user-images.githubusercontent.com/16419862/240609828-1b0a7ae1-7545-4f4c-9619-19ce2351f87d.png)
> 
> 
> kind of breaks the whole meeting page

should be resolved now, see https://github.com/lblod/frontend-gelinkt-notuleren/pull/462#issuecomment-1562407050

2023-05-25 09:59 UTC, abeforgit requested changes
getting this error when trying to open an agenda publication preview:
![image](https://github.com/lblod/frontend-gelinkt-notuleren/assets/16419862/971d2dd1-e7e5-4964-9a4b-ef20bc2daa2b)

2023-05-31 11:35 UTC, merged