GN-4358: addition of a document-type filter to the publication actions page
lblod/frontend-gelinkt-notuleren pull request #509
Opened 2023-06-26 10:40 UTC by elpoelma

### Overview
This PR adds a dropdown component to the publication actions page which allows users to filter on document type.
The values a user can select between are:
- Agenda
- Decision list
- Extract
- Document/Notulen

##### connected issues and PRs:
Jira ticket: https://binnenland.atlassian.net/browse/GN-4358?atlOrigin=eyJpIjoiOTViNmRjMzcwN2ExNGJkY2E5YTMyZTNkZDc2MzY1ODMiLCJwIjoiaiJ9
Design: https://www.figma.com/file/pW370BHe4ES5eN0vHhArA5/GN-4022?type=design&node-id=0-1&t=Ncms3NPhRgxXECZW-0

### How to test/reproduce
Visit the publication actions page and select a document type using the dropdown. Only the selected document type should be shown and the pagination should reset to page 0.

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint

2023-06-27 21:39 UTC, abeforgit commented
I know I'm being annoying but please stick to the jira format, so GN-4358 (will make parsing easier later)

2023-06-28 08:47 UTC, lagartoverde requested changes
The filtering is kept evern if you change meetings which can be confusing for the user because he can lose track of what is being filtered, apart from that everything else looks good 👍

2023-06-29 09:04 UTC, elpoelma commented
> The filtering is kept evern if you change meetings which can be confusing for the user because he can lose track of what is being filtered, apart from that everything else looks good +1

Should be solved with the `resetController` hook.

2023-06-29 11:40 UTC, abeforgit approved these changes

2023-07-03 08:03 UTC, merged