GN-4360: Unable to edit meeting after reverting signatures + no alert
lblod/frontend-gelinkt-notuleren pull request #513
Opened 2023-06-29 11:15 UTC by dkozickis

### Overview

#### Connected issues and PRs:
https://binnenland.atlassian.net/browse/GN-4360

### Setup
Usual setup, nothing special

### How to test/reproduce
You need to have a Notulen ready to be signed.

1. Sign with one user
2. Observer that you cannot edit the meeting anymore
3. Sign with second user
4. Remove the second user signature
5. Observe the notification
6. Observer that you cannot edit the meeting still
7. Remove the first signature
8. Observe there's no more notification
9. Observer that you now _can edit the meetinf_

See video at - https://share.cleanshot.com/JJVHDGlj

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2023-06-30 19:46 UTC, abeforgit requested changes
works afaict, some small code comments

2023-06-30 19:46 UTC, abeforgit commented on app/components/meeting-form.js
> +      'filter[:has-no:deleted]': 'yes',
this means you will only get signed resources that don't have the "deleted" field
If they have the field but it is false, you won't get them
```
        'filter[:or:][deleted]': false,
        'filter[:or:][:has-no:deleted]': 'yes',
```
afaik this is the way to get both

2023-06-30 19:46 UTC, abeforgit commented on app/components/meeting-form.js
> +    return arraySignedResources.toArray().some((resource) => !resource.deleted);
duplicate toArray here

2023-06-30 19:46 UTC, abeforgit commented on app/components/meeting-form.js
> +    return arraySignedResources.toArray().some((resource) => !resource.deleted);
and given the filter in the query, the some() should also not be needed

2023-06-30 19:46 UTC, abeforgit commented on app/controllers/meetings/publish/notulen.js
> +    const signedResources = await this.store.query('signed-resource', {
I would do the filter in the query

It's almost impossible to go wrong _in this specific scenario_ cause you can't really create more than 2 deleted signatures in sequence

but if there _would_ be `>pagesize` (aka more than 20) deleted signed resources that were newer than the last undeleted one, you would get no undeleted resources in your result.

...which is pretty much impossible here unless something goes quite badly wrong. But still, it's good practice to filter on the backend

2023-07-03 09:34 UTC, elpoelma approved these changes
Works as expected and the code seems pretty sane to me :)

2023-07-03 12:43 UTC, abeforgit approved these changes

2023-07-03 13:08 UTC, merged