Feature/agendapunten rework
lblod/frontend-gelinkt-notuleren pull request #60
Opened 2021-02-24 23:22 UTC by abeforgit

Complete rework of the agenda management components

Key points: 
- item list is rendered directly in the page, aka one modal less
- items are saved individually (no more store-and-save-later)
- thorough rewrite of the code

2021-02-25 09:07 UTC, Dietr commented
Looks good. Much more in line with the other modals on the meeting form page. I added some styling and removed some old webuniversum classes.

2021-02-25 09:08 UTC, Dietr approved these changes

2021-02-25 13:46 UTC, nvdk requested changes

2021-02-25 13:46 UTC, nvdk commented on app/templates/imported-documents/publish.hbs
> +                        <p class="smaller u-spacer">U kan dit document niet meer nietig verklaren, omdat de aanvullende agenda-manager al gepubliceerd werd.</p> wss niet nodig
woops, replaced a string too many ;)

2021-02-25 13:46 UTC, nvdk commented on app/templates/login.hbs
> +                <li>stel <strong>agenda-manager's</strong> op, bereid <strong>agendapunten</strong> voor en <strong>notuleer</strong> uw zitting;</li>
remove manager here

2021-02-25 13:46 UTC, nvdk commented on app/components/document-link-to-published.js
> +        return "Bekijk&nbsp;publieke&nbsp;agenda-manager";
remove manager here

2021-02-25 13:48 UTC, nvdk commented on app/components/agenda-manager/agenda-context.js
> +    const documentContainer = this.store.createRecord("document-container");
document container needs to have a folder and status set

2021-02-26 11:06 UTC, nvdk approved these changes

2021-02-26 11:06 UTC, merged