Bugfix/autofill variable bug
lblod/frontend-gelinkt-notuleren pull request #792
Opened 2024-12-06 11:46 UTC by lagartoverde

### Overview
The autofill variable bug described in GN-5210 was caused by the agendapoints.edit controller setting the plugins before the route was loaded and the current session object was filled. I reworked that interaction so nothing is called until everything has loaded correctly

##### connected issues and PRs:
GN-5210

### Setup
None

### How to test/reproduce
You can try reproducing the bug, basically if you create an IV, go to the first agendapoint and in the besluit snippet list you selected one of the options with the autofill variable the first time it should work, but if you refresh and do the same again it didn't work.
Now it always work, as the autofill plugin is not set up until everything has been loaded

### Challenges/uncertainties
Not enough knowledge of the headless editor so I think I did everything correctly so that also works, but please Elena verify :)

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-12-06 13:54 UTC, elpoelma commented
Just a small comment already, will do a full review after: putting the creation of a prosemirror schema in a dynamic getter can cause issues. I'll try to dig up the original PR where the change was introduced to move away from dynamic getters for schemas.

2024-12-06 15:04 UTC, abeforgit commented
gonna also leave this one out of todays hotfix, not so urgent and would be good to test

2024-12-10 10:09 UTC, lagartoverde commented on app/controllers/agendapoints/edit.js
> +    return this.agendapointEditor.citationPlugin;
This needs to be like this because the card makes reference to the plugin

2024-12-10 10:30 UTC, lagartoverde commented on app/templates/agendapoints/edit.hbs
> +  {{did-insert this.setSchemaAndPlugins}}
Done :)

2024-12-10 10:30 UTC, lagartoverde commented on app/controllers/agendapoints/edit.js
> +  }
Done :)

2024-12-13 10:43 UTC, elpoelma commented on app/controllers/agendapoints/edit.js
> +    return this.agendapointEditor.citationPlugin;
Yes I understand why it's needed, but making it a dynamic getter will break the citation-plugin.
As the `citationPlugin` you pass to the card is not the same one you pass to prosemirror.

2024-12-18 08:56 UTC, abeforgit requested changes

2024-12-18 08:56 UTC, abeforgit commented on app/controllers/agendapoints/edit.js
> +    const citationPlugin = this.agendapointEditor.citationPlugin;
so now this means that anywhere we use this service, we just have to remember to treat the citationPlugin property in this special way?
this doesn't seem like a good solution...
something is off here, we're making a fundamentally simple thing complicated
ember is not being very helpful in all this, but I do have some ideas, I'll have a look

2025-01-09 09:04 UTC, elpoelma approved these changes
Looks good now!
- Citation plugin triggers as expected
- The autovar functionality works across reloads

2025-01-13 09:12 UTC, merged