Add copy parts to the agendapoint
lblod/frontend-gelinkt-notuleren pull request #796
Opened 2024-12-12 10:33 UTC by lagartoverde

### Overview
Add a way of copying the parts of an agendapoint direclty from the agendapoint and not from the meeting

##### connected issues and PRs:
GN-5321

### Setup
None

### How to test/reproduce
Go to an agendapoint, in the file options you should have a copy decision parts button that should lead you to a new page where you can copy the decision parts

### Challenges/uncertainties
None

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-12-16 14:34 UTC, piemonkey requested changes
I feel like it doesn't make sense to duplicate this route (also template and controller, etc). To me it would make sense to have both sources use this new route instead of the old one. We'd then need to use a similar approach to when editing an agendapoint, where we use a query param to say which 'go back to' we display.

2024-12-18 09:00 UTC, abeforgit commented
> I feel like it doesn't make sense to duplicate this route (also template and controller, etc). To me it would make sense to have both sources use this new route instead of the old one. We'd then need to use a similar approach to when editing an agendapoint, where we use a query param to say which 'go back to' we display.

No I disagree. Duplicating the route is OK, and actually I think the query param shenanigans we do for the meeting are really bad. However, that doesn't mean we have to duplicate the _contents_ of the route
what this looks like it needs is to extract (most) of the copy page into a component, and then reference it in both routes

2024-12-18 09:04 UTC, abeforgit commented
ember routing fundamentally drives the logic of the app, it's (perhaps unfortunately) a bit more than just "this url will render this page"
I think the way they want you to think about routing is very "object oriented"
so two different ways of getting to the same page can have different routes imo, even if only to avoid the weird query param stuff

we have components to avoid duplication

2024-12-18 09:06 UTC, abeforgit requested changes
imo: keep the route, but avoid the duplication by extracting to a component (but don't move the data-loading logic out of the route, just pass it through instead of loading it in the component)

2025-01-02 12:09 UTC, elpoelma approved these changes
Keeping two different routes and defining the logic in a single component indeed seems best. Looks good to me! I can easily access the copy-page using the two approaches.

2025-01-02 14:26 UTC, merged