Feat/full rb copy
lblod/frontend-gelinkt-notuleren pull request #799
Opened 2024-12-30 09:52 UTC by lagartoverde

### Overview
Added copy screen to rb

##### connected issues and PRs:
GN-5300

### Setup
None

### How to test/reproduce
Go to regulatory attachments, notice you can now click on file options, copy parts, and the copy screen works as expected

### Challenges/uncertainties
In the config, the parts needs to be defined in order of specifity, didn't know how to solve this

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [ ] changelog
- [ ] npm lint
- [ ] no new deprecations

2024-12-31 08:46 UTC, piemonkey requested changes
I'm not 100% on the approach. I think it depends how much this is intended to be a thing to keep around or whether it's a relatively quick fix. I say this as my original version was intended as a quick fix to support exporting IV parts to paste into vendor software.

I found a couple of issues:

- Somehow, navigating back from the RS copy route doesn't work, just the location changes but the page does not
- It seems like just nesting an article in a chapter doesn't work. I need to insert a section and subsection too.

2025-01-10 10:50 UTC, abeforgit commented
> I'm not 100% on the approach. I think it depends how much this is intended to be a thing to keep around or whether it's a relatively quick fix. I say this as my original version was intended as a quick fix to support exporting IV parts to paste into vendor software.

@piemonkey 

So we talked this through and considered other approaches, all involving adding some extra knowledge into the nodespecs so we can more robustly parse them.

While it would work, we ultimately hit a wall of flexibility. E.g.: we want _some_ block-rdfa nodes to show up in these views, but not all. While we could then make that configurable on the template level, I feel that's really going too far with this feature.

Personally I'd like to see the need for this page disappear eventually, maybe by moving the copy buttons really _into_ the editor or making the default copy smarter, or just approach the actual problem that these pages solve in a different way (more direct integration with vendors or something)

I was already annoyed at the demand for adding the copy page to RBs as it seemed like a whim of the PMs without much thought into who is actually supposed to use them.

In short, I think its best to go ahead with the slightly hacky html selectors, they're error prone but also very flexible, and we can drop them on a dime when we get the chance

2025-01-15 10:37 UTC, abeforgit requested changes
still has the styling issue:

![image](https://github.com/user-attachments/assets/1adee527-38d0-4d2b-8548-a98ec0e1f11a)

2025-01-15 11:57 UTC, lagartoverde commented
Sorry I thought I had paragraphs in my tests, seems like I didn't after the latest changes

2025-01-20 16:45 UTC, elpoelma requested changes
Functionally, this PR makes sense and works well.
There are still some translation-related issues left.

The 'Copy title' button is a bit weird to me, as you're actually copying the content below the title, but that's also due to how weirdly a 'title' is implemented/defined.

2025-01-20 16:45 UTC, elpoelma commented on translations/nl-BE.yaml
> +  copy-rb: Copy full reglementaire bijlagen
This should be: 'Kopieer volledige reglementaire bijlage'

2025-01-23 09:03 UTC, merged