Feature/intermission
lblod/frontend-gelinkt-notuleren pull request #87
Opened 2021-04-19 14:41 UTC by lagartoverde

2021-04-19 14:43 UTC, lagartoverde commented
Please doublecheck the dutch translations there were some that weren't defined in the feature passport so maybe they are not correct. Also @Dietr wanted to tweak the design :)

2021-04-19 16:59 UTC, Windvis commented
@lagartoverde I think this should target the development branch. That branch has the updated CI config as well :smile:.

2021-04-20 16:00 UTC, Windvis requested changes

2021-04-21 09:03 UTC, lagartoverde commented on app/components/manage-intermissions/delete.hbs
> +          <label class="au-c-control au-c-control--checkbox">
Basically I copied over the delete block of the agenda component, and that wasn't using it, I will change it

2021-04-21 11:50 UTC, lagartoverde commented on app/components/manage-intermissions/index.hbs
> +            {{t "manageIntermissions.addInterruptionLabel"}}
I think the passport description changed, In the current specification this is no longer the case, I talked with dieter and confirmed we have the correct behavior now :)

2021-04-21 13:47 UTC, nvdk requested changes
some small issues with the english translation.

@Dietr do we need the confirmation on removal do you think? I'm personally not a fan in the agenda manager and even less so here :)

2021-04-21 13:47 UTC, nvdk commented on translations/en-us.yaml
> +  agreeQuestion: Are you sure you want to delete the agenda item?
```suggestion
  agreeQuestion: Are you sure you want to delete the intermission?
```

2021-04-21 13:47 UTC, nvdk commented on translations/en-us.yaml
> +  checkboxLabel: I understand that the agenda item will be irreversibly removed.
```suggestion
  checkboxLabel: I understand that the intermission will be irreversibly removed.
```

2021-04-21 13:54 UTC, nvdk commented on app/components/manage-intermissions/index.js
> +      startedAt: new Date()
nitpicking: I think it makes sense to default to the meeting startDate if that's available

2021-04-21 13:54 UTC, Dietr commented
> @Dietr do we need the confirmation on removal do you think? I'm personally not a fan in the agenda manager and even less so here :)

Not sure if we need it. For now I think it's best to keep it as is for consistency reasons. If we can rework the agendapoint delete at the same time I would prefer a simple delete button in the footer of the modal.

2021-04-22 08:42 UTC, nvdk commented
will merge once suggestiosn here and changes to backend have been merged, see https://github.com/lblod/notulen-prepublish-service/pull/20

2021-04-22 14:21 UTC, merged